version: '3.8'

services:
  # Laravel App Service (PHP)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www # Sync local backend code with container
    networks:
      - app-network

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80" # Map host port 80 to container port 80
    volumes:
      - ./frontend:/var/www/frontend # Sync local frontend code
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - app-network

# Define the network
networks:
  app-network:
    driver: bridge

# Define the volume for persistent DB data
volumes:
  db-data:
    driver: local