services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bmd-php
    volumes:
      - ./backend:/var/www/html
    networks: [bmd]

  nginx:
    image: nginx:stable-alpine
    container_name: bmd-nginx
    ports:
      - "8000:80"         # API reachable at http://localhost:8000
    volumes:
      - ./backend:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [php]
    networks: [bmd]

  db:
    image: mysql:8.0
    container_name: bmd-db
    environment:
      MYSQL_DATABASE: bookmydoc3
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # you said: no password
      # MYSQL_ROOT_PASSWORD: ""            # (not needed when allow empty)
    ports:
      - "3306:3306"       # optional: connect from host tools
    volumes:
      - bmd_mysql:/var/lib/mysql
    networks: [bmd]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bmd-front
    ports:
      - "5173:5173"       # Vite dev server
    environment:
      # Let your React app call the API in Docker
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks: [bmd]

volumes:
  bmd_mysql:

networks:
  bmd:
    driver: bridge
