services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8001"  # Use port 8001 inside the container and map it to 8000 on the host
    volumes:
      - .:/var/www
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_DATABASE=bookmydoc3
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bookmydoc3
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
